### PR TITLE
Target naming

### PR DESCRIPTION
**Pull request by jjceresa**
This PR address discussion in issue https://github.com/swami/libinstpatch/issues/3
about:
- `target naming`, 
- `binary file naming`,
- fixing coherency on path directory for installed include files.

### CODE REVIEW

**Comment by derselbst** [comment]
Having a `libinstpatch-1.so` on linux seems wrong. On linux the version is usually appended after the filename like `libinstpatch.so.1.1.0`. Suffixing the major version to the filename was meant for windows only. Sry, for the misunderstanding. I can fix this for linux, but this may take some time.

Also, I'm not quite sure whether it's correct to bump `LIB_VERSION_CURRENT`. This would indicate a API/ABI breakage on linux, which currently doesn't exist. I need to think about that.

**Comment by jjceresa** [comment]
>Sry, for the misunderstanding. I can fix this for linux, but this may take some time.
Also, I'm not quite sure whether it's correct to bump LIB_VERSION_CURRENT. This would indicate a API/ABI breakage on linux, which currently doesn't exist. I need to think about that.

No problem. As  it is a minor issue easy to fix, this can wait until we adopt a convention.

**Comment by jjceresa** [comment]
>Also, I'm not quite sure whether it's correct to bump LIB_VERSION_CURRENT. This would indicate a API/ABI breakage on linux, which currently doesn't exist.

You're right. In fact, i was confused by fluidsynth case in which `major library version` (LIB_VERSION_CURRENT) is equal to `major package version (i.e IPATCH_VERSION_MAJOR). I feel wrong and still don't see the purpose of `package version` and the relation (if any) between 'library version` and `package version`.

**Comment by derselbst** [comment]
I've fixed library naming on unix. There now is a `libinstpatch.so`. Please test whether there is a `libinstpatch-0.dll` on windows. Also I've removed the custom defined variables from libinstpatch.pc.in. Although supported, I don't think it's a good idea to use custom defined variables here.

**Comment by jjceresa** [comment]
>I've fixed library naming on unix. There now is a libinstpatch.so. 

Ok.

>Please test whether there is a libinstpatch-0.dll on windows. 

All is fine here. Tks.

>Also I've removed the custom.....Although supported, I don't think it's a good idea to use custom defined variables here.

Ok. I am fine with this target naming PR. Please, consider this ready to be merged.

**Pull request merged**
